apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gkxuwc9ws-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:6ae3bf6e2801668336c96bd3e0c300d4d9fab444@sha256:81298c977a29f4574330ebc1a300d4a1b9cf4a230ab6df94b990b19820691dac
          name: container-image
